# Cloudflare Pages 配置文件

name = "sociomint"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

# 环境变量 (公开变量)
[env.production.vars]
NODE_ENV = "production"
NEXT_PUBLIC_CHAIN_ID = "97"
NEXT_PUBLIC_RPC_URL = "https://data-seed-prebsc-1-s1.binance.org:8545/"
# 主网部署后改为:
# NEXT_PUBLIC_CHAIN_ID = "56"
# NEXT_PUBLIC_RPC_URL = "https://bsc-dataseed1.binance.org/"
NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID = "fced525820007c9c024132cf432ffcae"
NEXT_PUBLIC_SM_TOKEN_ADDRESS = "0xd7d7dd989642222B6f685aF0220dc0065F489ae0"
NEXT_PUBLIC_SM_EXCHANGE_ADDRESS = "0xF0c4729f07d7B2F03E2E2F2feED36386Dc8bFb8E"
NEXT_PUBLIC_MULTISIG_WALLET_ADDRESS = "0x681E8E1921778A450930Bc1991c93981FD0B1F24"
NEXT_PUBLIC_SUPABASE_URL = "https://kiyyhitozmezuppziomx.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpeXloaXRvem1lenVwcHppb214Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2OTA4NjgsImV4cCI6MjA1OTI2Njg2OH0.djjofAxZdg7EeRUixmhUomMOyIDkKU0exxhkW_PtBrg"
NEXT_PUBLIC_DISCORD_CLIENT_ID = "1377572072602996797"
NEXT_PUBLIC_APP_URL = "https://sociomint.top"
